ibm:
  mq:
    queue-manager: QM1
    channel: DEV.APP.SVRCONN
    conn-name: localhost(1414)
    user: app
    password: app
    queue: DEV.QUEUE.1
    application-name: payment-queue-kata
    ssl-cipher-suite: null

spring:
  jms:
    listener:
      concurrency: 1
